# Generated by Django 3.1.3 on 2020-12-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InnerUsers', models.IntegerField()),
                ('play', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InnerRoomNumber', models.IntegerField()),
                ('user_id', models.CharField(max_length=50)),
                ('user_ip', models.CharField(max_length=30)),
                ('Host', models.CharField(max_length=10)),
                ('haveCard', models.IntegerField()),
            ],
        ),
    ]
